name: Integration Tests CI Setup

on:
  workflow_call:
    inputs:
      PYTEST_ARGS:
        description: "Pytest run arguments to be passed for test execution"
        type: string
      JOB_NAME:
        description: "Name of the Github Action job. The jobs that we use are typically organized according to the test suite name."
        type: string

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Execute automated tests
        env:

        run: |
          unset https_proxy
          docker compose run -e PYTEST_ARGS='${{inputs.PYTEST_ARGS}}' 'cteleport-automated-tests'

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: docker-allure-test-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose -f docker-compose.yml down